In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = pd.read_csv('Titanic_for_ML.csv')
print('--Data load--')

--Data load--

In [3]:
print(f'Rows: {df.shape[0]} -- Columns: {df.shape[1]}')

Rows: 891 -- Columns: 26

In [4]:
df.head()

   Survived  Pclass  ...  AgeGroup_Adult  AgeGroup_Senior
0         0       3  ...               0                0
1         1       1  ...               1                0
2         1       3  ...               0                0
3         1       1  ...               0                0
4         0       3  ...               0                0

[5 rows x 26 columns]

In [5]:
#Features
X = df.drop(columns='Survived')
#Target
y = df['Survived']

In [6]:
#splitting data into 80% train and 20% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#checking the size of each set
print('--DATA CHECK--')
print(f'Number of Passangers in the train set: {X_train.shape[0]}')
print(f'Columns in the train set: {X_train.shape[1]}')
print(f'Number of Passangers in the test set: {y_test.shape[0]}')

--DATA CHECK--
Number of Passangers in the train set: 712
Columns in the train set: 25
Number of Passangers in the test set: 179

In [7]:
#creating model
model = LogisticRegression(max_iter=1000)
model.fit (X_train, y_train)
print('--done--')

--done--

In [8]:
#checking with the test set
prediction = model.predict(X_test)
accuracy = accuracy_score(y_test, prediction)

#checking accuracy score
print(f'Accuracy Score: {accuracy * 100:.2f}')

Accuracy Score: 82.68

In [9]:
#checking the coefficients
coefficients = pd.DataFrame({'Feature': X.columns, 'Points': model.coef_[0]})
coefficients = coefficients.sort_values(by='Points', ascending=False)
coefficients

                   Feature    Points
11            Title_Master  1.423753
5               Sex_female  0.870789
20          AgeGroup_Child  0.788799
14               Title_Mrs  0.777731
10                hasCabin  0.609153
19     FareCategory_Luxury  0.276382
7               Embarked_C  0.244471
22    AgeGroup_Young Adult  0.077574
18  FareCategory_Expensive  0.056471
8               Embarked_Q  0.020750
2                    Parch -0.097946
21           AgeGroup_Teen -0.110734
17     FareCategory_Medium -0.122467
16      FareCategory_Cheap -0.201384
12              Title_Miss -0.205214
4                  isAlone -0.251702
1                    SibSp -0.253677
9               Embarked_S -0.256219
24         AgeGroup_Senior -0.308969
3               FamilySize -0.342622
23          AgeGroup_Adult -0.437668
0                   Pclass -0.627226
15              Title_Rare -0.731684
6                 Sex_male -0.861788
13                Title_Mr -1.255584

**Note:** The train above was with the LogisticRegression Model, additionally the RandomForestClassifier was imported to predict with another model.

In [ ]:
#import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

#creating model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
print('done')

done

In [11]:
#checking with test set
rf_prediction = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, rf_prediction)
#checking the accuracy
print(f'Accuracy Score: {rf_accuracy*100:.2f}%')

Accuracy Score: 82.12%

In [12]:
#checking the feature importance from RandomForestClassifier
rf_importance = pd.DataFrame({'Feature': X.columns, 'Rating': rf_model.feature_importances_})
rf_importance = rf_importance.sort_values(by='Rating', ascending=False)
print(rf_importance)

                   Feature    Rating
6                 Sex_male  0.140113
0                   Pclass  0.102373
5               Sex_female  0.101266
13                Title_Mr  0.094842
3               FamilySize  0.075812
10                hasCabin  0.060326
1                    SibSp  0.048844
14               Title_Mrs  0.037880
2                    Parch  0.035143
12              Title_Miss  0.030456
19     FareCategory_Luxury  0.027566
9               Embarked_S  0.024622
17     FareCategory_Medium  0.023811
20          AgeGroup_Child  0.023660
22    AgeGroup_Young Adult  0.023453
18  FareCategory_Expensive  0.022864
7               Embarked_C  0.022393
16      FareCategory_Cheap  0.020643
23          AgeGroup_Adult  0.018153
21           AgeGroup_Teen  0.015475
4                  isAlone  0.014008
11            Title_Master  0.012486
8               Embarked_Q  0.011521
15              Title_Rare  0.006630
24         AgeGroup_Senior  0.005660

In [19]:
#using KNeighborsClassfier 
from sklearn.neighbors import KNeighborsClassifier

#creating the model and made the fit
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
print('done')

done

In [18]:
#checking with the test set
knn_model = knn_model.predict(X_test)
knn_accur = accuracy_score(y_test, knn_model)

#Checking the score
print(f'Score: {knn_accur*100:.2f}%')

Score: 80.45%