# Superstore Analysis
## Feature Engineering
* **Goal:** Filling missing values and preparing Dataset for ML

In [42]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
# Safe Data Loading with raw dataset

file_path = '../data/superstore.csv'

try:
    df = pd.read_csv(file_path, encoding='latin1')
    print('Load successfully')
except FileNotFoundError:
    print(f'File not found - check {file_path}')
except Exception as e:
    print(f'Unexpected Error - check {e}')

Load successfully

In [44]:
# Inspection of Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

**Note:** No missing values

In [45]:
# Check Metrics
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [46]:
# Check DF Header
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [63]:
# Check for duplicates
df.duplicated().sum()

np.int64(0)

**Note:** No Duplicates

In [48]:
# Convert Order Date and Ship Date into pd.datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%m/%d/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%m/%d/%Y')

In [49]:
# Create new feature - Shipping Days
df['Shipping_Days'] = df['Ship Date'] - df['Order Date']

# Check for result
df['Shipping_Days'].value_counts()

Shipping_Days
4 days    2774
5 days    2169
2 days    1334
6 days    1203
3 days    1005
7 days     621
0 days     519
1 days     369
Name: count, dtype: int64

In [50]:
# Check Metrics of Shipping Days
df['Shipping_Days'].describe()

count                         9994
mean     3 days 22:59:46.311787072
std      1 days 17:56:29.766161104
min                0 days 00:00:00
25%                3 days 00:00:00
50%                4 days 00:00:00
75%                5 days 00:00:00
max                7 days 00:00:00
Name: Shipping_Days, dtype: object

In [51]:
# Convert Timedelta into days
df['Shipping_Days'] = df['Shipping_Days'].dt.days

# Check the result
df['Shipping_Days'].value_counts()

Shipping_Days
4    2774
5    2169
2    1334
6    1203
3    1005
7     621
0     519
1     369
Name: count, dtype: int64

**Note:**
Supply chain efficiency and fulfillment speed are primary drivers of customer satisfaction and long-term retention. By calculating the `Shipping_Days` it is possible to transform raw logistical data into a measurable key performance indicator (KPI) for the supply chain.

In [52]:
# Extracting Year, Month and DayofWeek from Order Date
df['Order_Year'] = df['Order Date'].dt.year
df['Order_Month'] = df['Order Date'].dt.month
df['Order_DayOfWeek'] = df['Order Date'].dt.dayofweek

# Check for result
df[['Order_Year', 'Order_Month', 'Order_DayOfWeek']].head()

   Order_Year  Order_Month  Order_DayOfWeek
0        2016           11                1
1        2016           11                1
2        2016            6                6
3        2015           10                6
4        2015           10                6

**Note:** Transforming raw date strings into numerical components for capturing patterns.

In [ ]:
# Create new feature for Orders on Weekend
df['is_weekend_order'] = df['Order_DayOfWeek'].isin([5,6]).astype(int)

# Check the result
df['is_weekend_order'].value_counts()

Is_Weekend_Order
0    6629
1    3365
Name: count, dtype: int64

**Note:** Purchasing behavior on weekends often diverges fundamentally from weekday transactions. This binary feature isolates the distinct customer personas and operational requirements.

In [ ]:
# Create new feature 'is_profitable' if profit is > 0
df['is_profitable'] = (df['Profit'] > 0).astype(int)

# Check for result
df['is_profitable'].value_counts()

isProfitable
1    8058
0    1936
Name: count, dtype: int64

**Note:** Margin maximization and cost control are fundamental to business viability.

In [64]:
# Create new feature 'profit_margin' by dividing profit with sales
df['profit_margin'] = df['Profit'] / df['Sales']

**Note:** While absolute revenue (`Sales`) and total `Profit` reveal the scale of cash flowing through the business, they fail to measure true financial efficiency. The `profit_margin` standardizes profitability as a ratio.