# Real Estate Analysis
## Exploratory Data Analysis
* **Goal:** TBA

In [2]:
# Import libraries for Exploratory Analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Safe Dataloading
real_estate_data = ('../data/world_real_estate_data(147k).csv')

try:
    df = pd.read_csv(real_estate_data)
    print(f'File Loaded successfully')
except FileNotFoundError:
    print(f'File Not Found - check {real_estate_data}')
except Exception as e:
    print(f'Error occured - check {e}')

File Loaded successfully

In [4]:
# Inspection of Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147536 entries, 0 to 147535
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   title                       147536 non-null  object
 1   country                     147406 non-null  object
 2   location                    147405 non-null  object
 3   building_construction_year  64719 non-null   float64
 4   building_total_floors       68224 non-null   float64
 5   apartment_floor             54592 non-null   float64
 6   apartment_rooms             74178 non-null   float64
 7   apartment_bedrooms          36982 non-null   float64
 8   apartment_bathrooms         55973 non-null   float64
 9   apartment_total_area        141796 non-null  object
 10  apartment_living_area       27712 non-null   object
 11  price_in_USD                144961 non-null  float64
 12  image                       147536 non-null  object
 13  url                         147536 non-null  object
dtypes: float64(7), object(7)
memory usage: 15.8+ MB

In [5]:
# Check columns
print(f'Rows: {df.shape[0]} -- Columns: {df.shape[1]}')

Rows: 147536 -- Columns: 14

In [6]:
# Check metrics of Dataset

df.describe()

,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,price_in_USD
count,64719.000000,68224.000000,54592.000000,74178.000000,36982.000000,55973.000000,1.449610e+05
mean,1996.921754,8.575692,5.791709,2.572097,2.289222,1.364229,4.121722e+05
std,157.527635,8.356781,5.541368,1.319545,18.276913,0.745019,8.420984e+05
min,1.000000,-1.000000,-2.000000,-1.000000,-1.000000,1.000000,0.000000e+00
25%,2004.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.054200e+05
50%,2021.000000,5.000000,4.000000,2.000000,2.000000,1.000000,1.902120e+05
75%,2024.000000,14.000000,8.000000,3.000000,3.000000,2.000000,3.989300e+05
max,2316.000000,124.000000,202.000000,124.000000,2009.000000,43.000000,3.060283e+07

**Note:** Further insepction of 'building_total_floors', 'apartment_floor' and 'appartment_bedrooms', because of negative min values.

In [7]:
# Inspection of first 5 rows

df.head()

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...

In [8]:
# Check missing values

df.isna().sum()

title                              0
country                          130
location                         131
building_construction_year     82817
building_total_floors          79312
apartment_floor                92944
apartment_rooms                73358
apartment_bedrooms            110554
apartment_bathrooms            91563
apartment_total_area            5740
apartment_living_area         119824
price_in_USD                    2575
image                              0
url                                0
dtype: int64

**Note:** Missing values need to be handled in FE.

In [17]:
# Checking the negativ values for 'building_total_floors'
print(df['building_total_floors'].min())
print(df['building_total_floors'].value_counts().sort_index().head())

-1.0
building_total_floors
-1.0        1
 1.0    10198
 2.0     8209
 3.0     6158
 4.0     4493
Name: count, dtype: int64

In [16]:
# Checking negativ values for 'apartment_floor'
print(df['apartment_floor'].min())
print(df['apartment_floor'].value_counts().sort_index().head())

-2.0
apartment_floor
-2.0       1
-1.0     414
 1.0    9257
 2.0    7994
 3.0    6847
Name: count, dtype: int64

In [18]:
# Checking negativ values for 'apartment_bedrooms'
print(df['apartment_bedrooms'].min())
print(df['apartment_bedrooms'].value_counts().sort_index().head())

-1.0
apartment_bedrooms
-1.0       37
 1.0    11269
 2.0    14433
 3.0     8550
 4.0     1968
Name: count, dtype: int64