# Real Estate Analysis
## Feature Engineering
* **Goal:** Prepare and transform the dataset for property price prediction

This notebook prepares the cleaned dataset for machine learning models.

In [31]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
# Safe Dataloading
real_estate_data = ('../data/world_real_estate_data(147k).csv')

try:
    df = pd.read_csv(real_estate_data)
    print(f'File Loaded successfully')
except FileNotFoundError:
    print(f'File Not Found - check {real_estate_data}')
except Exception as e:
    print(f'Error occured - check {e}')

File Loaded successfully

In [33]:
# Inspection of Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147536 entries, 0 to 147535
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   title                       147536 non-null  object
 1   country                     147406 non-null  object
 2   location                    147405 non-null  object
 3   building_construction_year  64719 non-null   float64
 4   building_total_floors       68224 non-null   float64
 5   apartment_floor             54592 non-null   float64
 6   apartment_rooms             74178 non-null   float64
 7   apartment_bedrooms          36982 non-null   float64
 8   apartment_bathrooms         55973 non-null   float64
 9   apartment_total_area        141796 non-null  object
 10  apartment_living_area       27712 non-null   object
 11  price_in_USD                144961 non-null  float64
 12  image                       147536 non-null  object
 13  url                         147536 non-null  object
dtypes: float64(7), object(7)
memory usage: 15.8+ MB

In [34]:
df.head()

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...

In [35]:
print(f'Rows: {df.shape[0]} -- Columns:{df.shape[1]}')

Rows: 147536 -- Columns:14

In [36]:
# Check missing values
df.isna().sum().sort_values(ascending=False)

apartment_living_area         119824
apartment_bedrooms            110554
apartment_floor                92944
apartment_bathrooms            91563
building_construction_year     82817
building_total_floors          79312
apartment_rooms                73358
apartment_total_area            5740
price_in_USD                    2575
location                         131
country                          130
title                              0
image                              0
url                                0
dtype: int64

In [37]:
# Check mean missing values
df.isna().mean().sort_values(ascending=False) * 100

apartment_living_area         81.216788
apartment_bedrooms            74.933576
apartment_floor               62.997506
apartment_bathrooms           62.061463
building_construction_year    56.133418
building_total_floors         53.757727
apartment_rooms               49.722102
apartment_total_area           3.890576
price_in_USD                   1.745337
location                       0.088792
country                        0.088114
title                          0.000000
image                          0.000000
url                            0.000000
dtype: float64

In [38]:
# Drop missing rows from price_in_USD
df = df.dropna(subset=['price_in_USD'])

In [39]:
# Check 
df['price_in_USD'].isna().sum()

np.int64(0)

In [40]:
# Drop apartment living area, because of 81% missing values
df = df.drop(columns='apartment_living_area')

In [41]:
# Check missing values
df.isna().sum().sort_values(ascending=False)

apartment_bedrooms            108397
apartment_floor                90832
apartment_bathrooms            89173
building_construction_year     80665
building_total_floors          77376
apartment_rooms                71350
apartment_total_area            4706
location                         131
country                          130
title                              0
price_in_USD                       0
image                              0
url                                0
dtype: int64

In [42]:
# Drop url, image and title cols
df = df.drop(columns=['url', 'image', 'title'])

In [43]:
# Check shape
print(f'Rows: {df.shape[0]} -- Columns: {df.shape[1]}')

Rows: 144961 -- Columns: 10

In [44]:
df.isna().sum().sort_values(ascending=False)

apartment_bedrooms            108397
apartment_floor                90832
apartment_bathrooms            89173
building_construction_year     80665
building_total_floors          77376
apartment_rooms                71350
apartment_total_area            4706
location                         131
country                          130
price_in_USD                       0
dtype: int64

In [45]:
# Check nunique on country and location
df[['country', 'location']].nunique()

country       27
location    7188
dtype: int64

In [46]:
# Correlation check for missing values
missing_feat = [
    'apartment_bedrooms',
    'apartment_floor',
    'apartment_bathrooms',
    'building_construction_year',
    'building_total_floors',
    'apartment_rooms',
    'apartment_total_area'
]

df[missing_feat].isna().corr()

,apartment_bedrooms,apartment_floor,apartment_bathrooms,building_construction_year,building_total_floors,apartment_rooms,apartment_total_area
apartment_bedrooms,1.000000,-0.041742,0.410535,-0.131587,-0.056015,0.143256,-0.015684
apartment_floor,-0.041742,1.000000,0.194201,0.302069,0.647568,0.545608,0.108573
apartment_bathrooms,0.410535,0.194201,1.000000,0.238118,0.029189,0.406614,0.044087
building_construction_year,-0.131587,0.302069,0.238118,1.000000,0.388751,0.236128,0.008015
building_total_floors,-0.056015,0.647568,0.029189,0.388751,1.000000,0.408635,0.106745
apartment_rooms,0.143256,0.545608,0.406614,0.236128,0.408635,1.000000,0.116996
apartment_total_area,-0.015684,0.108573,0.044087,0.008015,0.106745,0.116996,1.000000

In [47]:
# Change apartment total area into float
df['apartment_total_area_analysis'] = (
    df['apartment_total_area']
    .str.replace(' m²', '', regex=False)
    .str.replace(' ' , '', regex=False)
    .astype(float)
)

In [48]:
# Exclude extreme outliers
df['apartment_total_area_analysis'] = df[
    'apartment_total_area_analysis'
].where(df['apartment_total_area_analysis'] <= 500
)

In [49]:
df['apartment_rooms_analysis'] = df['apartment_rooms'].where(
    df['apartment_rooms'].between(1, 10)
)

In [50]:
df['apartment_bedrooms_analysis'] = df['apartment_bedrooms'].where(
    df['apartment_bedrooms'].between(1, 10)
)

In [51]:
df['apartment_bathrooms_analysis'] = df['apartment_bathrooms'].where(
    df['apartment_bathrooms'].between(1, 10)
)

In [52]:
df['building_construction_year_analysis'] = df[
    'building_construction_year'
].where(
    df['building_construction_year'].between(1800, 2028)
)

In [53]:
df['apartment_floor_analysis'] = df['apartment_floor'].where(
    ~(
        (df['apartment_floor'] > df['building_total_floors']) &
        (df['building_total_floors'].notna())
    )
)

In [54]:
df['apartment_floor_analysis'] = df[
    'apartment_floor_analysis'
].where(
    df['apartment_floor_analysis'] >= -1
)

In [55]:
analysis_features = [
    'apartment_total_area_analysis',
    'apartment_rooms_analysis',
    'apartment_bedrooms_analysis',
    'apartment_bathrooms_analysis',
    'building_construction_year_analysis',
    'apartment_floor_analysis'
]

df[analysis_features].describe()

,apartment_total_area_analysis,apartment_rooms_analysis,apartment_bedrooms_analysis,apartment_bathrooms_analysis,building_construction_year_analysis,apartment_floor_analysis
count,136567.000000,73534.000000,36493.000000,55769.000000,63862.000000,53029.000000
mean,116.223180,2.560163,2.103965,1.358819,2009.274357,5.806653
std,89.829601,1.104530,1.001336,0.668076,25.177245,5.465215
min,1.000000,1.000000,1.000000,1.000000,1800.000000,-1.000000
25%,56.000000,2.000000,1.000000,1.000000,2005.000000,2.000000
50%,86.000000,2.000000,2.000000,1.000000,2022.000000,4.000000
75%,144.000000,3.000000,3.000000,2.000000,2024.000000,8.000000
max,500.000000,10.000000,10.000000,10.000000,2028.000000,90.000000

In [56]:
df[analysis_features].isna().sum().sort_values(ascending=False)

apartment_bedrooms_analysis            108468
apartment_floor_analysis                91932
apartment_bathrooms_analysis            89192
building_construction_year_analysis     81099
apartment_rooms_analysis                71427
apartment_total_area_analysis            8394
dtype: int64

In [57]:
# Filling apartment_total_area_analysis with median
df['apartment_total_area_analysis'] = (
    df['apartment_total_area_analysis']
    .fillna(df['apartment_total_area_analysis'].median())
)

In [58]:
# Check missing values
df[analysis_features].isna().sum().sort_values(ascending=False)

apartment_bedrooms_analysis            108468
apartment_floor_analysis                91932
apartment_bathrooms_analysis            89192
building_construction_year_analysis     81099
apartment_rooms_analysis                71427
apartment_total_area_analysis               0
dtype: int64

In [59]:
# Create missing value indicator column
df['apartment_rooms_missing'] = (
    df['apartment_rooms_analysis'].isna().astype(int)
)

In [ ]:
# Fill the missing values in room analysis with median
df['apartment_rooms_analysis'] = (
    df['apartment_rooms_analysis']
    .fillna(df['apartment_rooms_analysis'].median())
)

In [62]:
# Create missing value indicator column
df['apartment_bedrooms_missing'] = (
    df['apartment_bedrooms_analysis'].isna().astype(int)
)

# Fill the missing values in bedrooms analysis with median
df['apartment_bedrooms_analysis'] = (
    df['apartment_bedrooms_analysis']
    .fillna(df['apartment_bedrooms_analysis'].median())
)